
#
# Adding this file to the "eclipse-kapua" project will open up the
# Elasticsearch REST API.
#

apiVersion: v1
kind: Route
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  to:
    kind: Service
    name: elasticsearch
  port:
    targetPort: http
